### ISSUE TITLE
Validate on Submit

### ISSUE THREAD

**Issue by psenechal** [xtreamsrl/ngx-validation-errors#2]
Hi Luca,

Now that I can get the validation messages to display in lazy loaded modules, I have a new question for you.

Currently, the validation messages display when the input field is touched, dirty, and invalid; however, if the user simply clicks Submit without touching the input fields, the required validators don't fire.

Is there a way to make the validators fire on Submit of the form in addition to or instead of touched/dirty/invalid?

The other solution is just to disable the Submit button until the form is valid, but I'd rather avoid that because I have some rather long forms and complicated validations that I would like to fire on submit. I totally wouldn't mind if they fired on Submit AND touched/dirty/invalid though.

Thanks for the assistance!

**Comment by rams23** [comment]
Currently there is no such functionality. As there is no such thing in angular reactive form neither. My suggestion is to mark all form controls touched on submit interating on the form group

**Comment by psenechal** [comment]
Hi Luca,
Thanks for the suggestion. I created a Directive with the following code:

import { Directive, HostListener, Input } from '@angular/core';
import { FormArray, FormGroup } from '@angular/forms';

@Directive({
  selector: '[appFormSubmit]'
})
export class FormSubmitDirective {

  @Input()
  private formGroup: FormGroup;

  constructor() { }

  @HostListener('submit', ['$event'])
  onSubmit(event: Event) {
    this.markControlsDirty(this.formGroup);
  }

  private markControlsDirty(group: FormGroup | FormArray): void {
    Object.keys(group.controls).forEach((key: string) => {
      const abstractControl = group.controls[key];

      if (abstractControl instanceof FormGroup || abstractControl instanceof FormArray) {
        this.markControlsDirty(abstractControl);
      } else {
        abstractControl.markAsDirty();
        abstractControl.markAsTouched();
      }
    });
  }
}

and attached it to the forms using:

`appFormSubmit="formGroupName"`

The forms now show the validation on Submit

**Comment by rams23** [comment]
Great! If you agree I can add it in the library

**Comment by psenechal** [comment]
Absolutely...please feel free to use it any way you like.
