### ISSUE TITLE
Function calls are not supported in decorators

### ISSUE THREAD

**Issue by psenechal** [xtreamsrl/ngx-validation-errors#4]
Hi Luca,

I seem to be getting an error when compiling my project with the --prod flag. The error is:

`ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'NgxValidationErrorsModule' was called.
Unexpected value 'undefined' imported by the module 'AppModule in C:/app-dev/other-sources/gotbrix-app/src/app/app.module.ts'
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'NgxValidationErrorsModule' was called.`

The import in my app.module.ts file is:

`    NgxValidationErrorsModule.forRoot({
      errorComponent: CustomErrorsComponent as any
    }),`

I don't have any problems when running the project locally...only when doing a prod build. Any ideas on why this might be occurring? Thanks.

**Comment by zhygis** [comment]
Hello,
@psenechal this happens, that you are building production version, ng build --prod and NgxValidationErrorsModule,forRoot() has some logic prior to a return statement. All logic prior to return module statement is interpreted as function in js. So in general everything must be static in your forRoot() method. It can be achieved by using injection tokens. As in this particular case, you can fix it, by injecting argument as token and using factory method provide validation errors config:

`export const ValidationErrorsConfigObject = new InjectionToken('ValidationErrorsConfigObject');
export function createValidationErrorsConfig(config: ValidationErrorsConfig): ValidationErrorsConfig {
    const currentConfig = {
        defaultContext: 'general',
        errorComponent: InputErrorsComponent as any,
        defaultResources: GeneralResources
    } as ValidationErrorsConfig;

    if (config) {
        if (config.defaultContext) {
            currentConfig.defaultContext = config.defaultContext;
        }

        if (config.errorComponent) {
            currentConfig.errorComponent = config.errorComponent;
        }
        if (config.defaultResources) {
            currentConfig.defaultResources = config.defaultResources;
        }
    }

    return currentConfig;
}
@NgModule({
    declarations: [InputErrorsComponent, FormFieldContainerComponent, ValidationContextComponent],
    imports: [CommonModule, FormsModule, ReactiveFormsModule],
    exports: [InputErrorsComponent, FormFieldContainerComponent, ValidationContextComponent],
    entryComponents: [InputErrorsComponent]
})
export class ValidationErrorsModule {
    static forRoot(config?: ValidationErrorsConfig): ModuleWithProviders {
        return {
            ngModule: ValidationErrorsModule,
            providers: [
                { provide: ValidationErrorsConfigObject, useValue: config },
                { provide: ITranslateService, useClass: DefaultTranslateService },
                {
                    provide: VALIDATION_ERROR_CONFIG,
                    useFactory: createValidationErrorsConfig,
                    deps: [ValidationErrorsConfigObject]
                }
            ]
        };
    }
}`
This fix should be applied to NgxVallidationErrorsModule
Hope that was helpful.

**Comment by rams23** [comment]
Thanks @zhygis for the hint! I updated the library using the factory and tested the AOT build. @psenechal sorry for late reply, can you retry  after updating to 0.0.4?

**Comment by psenechal** [comment]
Hi Luca...I'll have to try this when I get home tonight on a different computer. My work PC seems to suddenly by throwing errors with ngUniversal and ngPwa and I can't seem to figure out what's going on. The Mac at home didn't seem to have any problems with those dependencies

**Comment by psenechal** [comment]
I rolled back those packages to the previous version and it resolved the issue. I did a production build with the 0.0.4 version and everything compiled successfully.

I ran locally and everything appears to still be working properly.

Thanks for the update!
